### ISSUE TITLE
Error in the Conclusion section

### ISSUE THREAD

**Issue by gnappo1** [learn-co-curriculum/python-p3-re-module#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/the-re-module?module_item_id=468002

### Concern

In the Conclusion section, the following line seems to mention the incorrect method:

search(), match(), and **findall**() check for a single match in your search string, returning re.Match objects if a match is found.

### Suggested Changes

Should we replace it with the following line:

search(), match(), and **fulmatch**() check for a single match in your search string, returning re.Match objects if a match is found.

**Comment by professor-ben** [comment]
Thanks for catching this! It is fixed in the blueprint and should show up in the instructor/coach course later today.

-Ben
